[project]
name = "myasa"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.8",
    "napari[all]>=0.6.6",
    "numpy>=2.4.2",
    "pyarrow>=24.0.0",
    "pyglm>=2.8.3",
    "scikit-learn>=1.8.0",
    "scipy>=1.17.0",
    "setuptools==81.0",
    "tensorboard>=2.20.0",
    "torch>=2.10.0",
    "torchvision>=0.25.0",
    "wandb>=0.26.1",
]
